import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    'intro',
    {
      type: 'category',
      label: 'White-Label App Integration',
      items: [
        'guides/white-label/quickstart',
        'guides/white-label/authentication',
      ],
    },
    {
      type: 'category',
      label: 'PMS Integration',
      items: [
        'guides/pms/quickstart',
      ],
    },
    'guides/concepts',
    'guides/error-handling',
  ],
  apiReferenceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api-reference',
    },
  ],
};

export default sidebars;
